// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPw5zfc_RH4uu4UNhkejimLDsc_u0NoZc',
    appId: '1:310564396725:web:1365442a776824916428fc',
    messagingSenderId: '310564396725',
    projectId: 'myschoolapp-73bd1',
    authDomain: 'myschoolapp-73bd1.firebaseapp.com',
    databaseURL: 'https://myschoolapp-73bd1.firebaseio.com',
    storageBucket: 'myschoolapp-73bd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-gSmVVi-Rxt1g22k0wdXtrsEKBR9DzPQ',
    appId: '1:310564396725:android:91d42e5224abe9556428fc',
    messagingSenderId: '310564396725',
    projectId: 'myschoolapp-73bd1',
    databaseURL: 'https://myschoolapp-73bd1.firebaseio.com',
    storageBucket: 'myschoolapp-73bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnkCR79qxRBqSu5zQSPaxYcsRsxWwZ8fY',
    appId: '1:310564396725:ios:87c69f2f1309858a6428fc',
    messagingSenderId: '310564396725',
    projectId: 'myschoolapp-73bd1',
    databaseURL: 'https://myschoolapp-73bd1.firebaseio.com',
    storageBucket: 'myschoolapp-73bd1.appspot.com',
    androidClientId: '310564396725-5c3p78uposcj9nl8n3vdva80n7b9k8eo.apps.googleusercontent.com',
    iosBundleId: 'com.myschoolcl.appmyschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnkCR79qxRBqSu5zQSPaxYcsRsxWwZ8fY',
    appId: '1:310564396725:ios:ab00aeaa329b737f6428fc',
    messagingSenderId: '310564396725',
    projectId: 'myschoolapp-73bd1',
    databaseURL: 'https://myschoolapp-73bd1.firebaseio.com',
    storageBucket: 'myschoolapp-73bd1.appspot.com',
    androidClientId: '310564396725-5c3p78uposcj9nl8n3vdva80n7b9k8eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.appmyschool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPw5zfc_RH4uu4UNhkejimLDsc_u0NoZc',
    appId: '1:310564396725:web:6524d299013661526428fc',
    messagingSenderId: '310564396725',
    projectId: 'myschoolapp-73bd1',
    authDomain: 'myschoolapp-73bd1.firebaseapp.com',
    databaseURL: 'https://myschoolapp-73bd1.firebaseio.com',
    storageBucket: 'myschoolapp-73bd1.appspot.com',
  );
}
